"""create_slides_table

Revision ID: fe91e4902933
Revises:
Create Date: 2025-05-31 13:40:02.028457  # Will be the execution date, not this placeholder

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe91e4902933'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('specific_prompt', sa.String(), nullable=True),
    sa.Column('suggested_messages', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slides_id'), 'slides', ['id'], unique=False)
    op.create_index(op.f('ix_slides_order'), 'slides', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_order'), table_name='slides')
    op.drop_index(op.f('ix_slides_id'), table_name='slides')
    op.drop_table('slides')
    # ### end Alembic commands ###
